name: Deploy DAG

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Deploy DAG's to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.TARGET_SECRET }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "dags/"
          REMOTE_HOST: ${{ secrets.TARGET_HOSTNAME }}
          REMOTE_PORT: ${{ secrets.TARGET_PORT }}
          REMOTE_USER: ${{ secrets.TARGET_USER }}
          TARGET: ${{ secrets.TARGET_DIR }}
          EXCLUDE: "/dags/"

